version: '2.1'

networks:
  monitor-net:
    driver: bridge

volumes:
  grafana_data: {}

services:
  grafana:
    image: grafana/grafana:6.7.6
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    expose:
      - 3000
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  caddy:
    image: stefanprodan/caddy
    container_name: caddy
    ports:
      - "3000:3000"
    volumes:
      - ./caddy:/etc/caddy
    environment:
      - ADMIN_USER=${CANDY_ADMIN_USER}
      - ADMIN_PASSWORD=${CANDY_ADMIN_PASSWORD}
    restart: unless-stopped
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"